<?php

include '../auth.php';
require_once '../image_storage.php';
protect_page(0); // Only allow customers to access this page


$me = $_SESSION['swapy_session'];

$user_res = mysqli_query(
    $conn,
    "SELECT * FROM users WHERE username = '$me'"
);

$user_data = mysqli_fetch_assoc($user_res);

if (isset($_POST['update_profile'])) {

    $newBio = mysqli_real_escape_string(
        $conn,
        $_POST['bio'] ?? ''
    );

    $newPic = trim($_POST['pic_base64'] ?? '');
    $removeProfileImage = isset($_POST['remove_profile_image'])
        && $_POST['remove_profile_image'] === '1';
    $newPicPath = '';
    $newPicData = '';
    $newPicMime = '';

    $uploadedProfileImage = read_uploaded_image($_FILES['profile_image'] ?? null);
    if ($uploadedProfileImage === false && !$removeProfileImage) {
        header("Location: profile.php?error=invalid_image");
        exit();
    }

    if ($uploadedProfileImage !== null && !$removeProfileImage) {
        $newPicData = $uploadedProfileImage['image_data'];
        $newPicMime = $uploadedProfileImage['mime_type'];
        $savedPic = save_data_uri_fallback(
            'data:' . $newPicMime . ';base64,' . base64_encode($newPicData),
            __DIR__ . '/uploads'
        );
        if ($savedPic === null) {
            header("Location: profile.php?error=invalid_image");
            exit();
        }
        $newPicPath = $savedPic['path'];
    } elseif ($newPic !== '' && !$removeProfileImage) {
        // Keep accepting the data URL generated by older versions of the form.
        $savedPic = save_data_uri_fallback($newPic, __DIR__ . '/uploads');
        if ($savedPic === null) {
            header("Location: profile.php?error=invalid_image");
            exit();
        }
        $newPicPath = $savedPic['path'];
        $newPicData = $savedPic['image_data'];
        $newPicMime = $savedPic['mime_type'];
    }

    $sql = "UPDATE users SET bio='$newBio'";

    if ($removeProfileImage) {
        $sql .= ", pic=NULL";
    } elseif ($newPicPath !== '') {
        $sql .= ", pic='" . mysqli_real_escape_string($conn, $newPicPath) . "'";
    }

    $sql .= " WHERE username='" . mysqli_real_escape_string($conn, $me) . "'";

    if (mysqli_query($conn, $sql)) {
        if ($newPicData !== '') {
            save_image_blob($conn, 'user', (int)$user_data['id'], $newPicMime, $newPicData);
        } elseif ($removeProfileImage && ensure_image_blob_table($conn)) {
            mysqli_query(
                $conn,
                "DELETE FROM swapy_image_blobs
                 WHERE entity_type = 'user' AND entity_id = " . (int)$user_data['id']
            );
        }

        header("Location: profile.php?success=profile_updated");
    } else {
        header("Location: profile.php?error=profile_update_failed");
    }

    exit();
}

if (isset($_POST['edit_item'])) {

    $p_id = (int)$_POST['p_id'];

    $title = mysqli_real_escape_string(
        $conn,
        $_POST['title']
    );

    $desc = mysqli_real_escape_string(
        $conn,
        $_POST['description']
    );

    mysqli_query(
        $conn,
        "
        UPDATE posts
        SET title='$title',
            description='$desc'
        WHERE id=$p_id
        AND author='$me'
        "
    );

    header("Location: profile.php");
    exit();
}

if (isset($_GET['delete_id'])) {

    $del_id = (int)$_GET['delete_id'];

    // A post can be referenced by chats and delivery requests. Delete those
    // dependent rows in one transaction before deleting the owned post, so a
    // failed child delete cannot leave the database half-cleaned.
    $owned_post = mysqli_query(
        $conn,
        "SELECT id FROM posts WHERE id = $del_id AND author = '$me' LIMIT 1"
    );

    if ($owned_post && mysqli_num_rows($owned_post) === 1) {
        $has_image_blob_table = ensure_image_blob_table($conn);
        $delete_ok = true;

        mysqli_begin_transaction($conn);

        $dependent_queries = [
            "DELETE FROM chats WHERE item_id = $del_id",
            "DELETE FROM delivery_request WHERE item_id = $del_id"
        ];

        if ($has_image_blob_table) {
            $dependent_queries[] = "
                DELETE FROM swapy_image_blobs
                WHERE entity_type = 'post' AND entity_id = $del_id
            ";
        }

        $dependent_queries[] = "
            DELETE FROM posts
            WHERE id = $del_id AND author = '$me'
        ";

        foreach ($dependent_queries as $delete_query) {
            if (!mysqli_query($conn, $delete_query)) {
                $delete_ok = false;
                error_log(
                    'Swapy post deletion failed for post ' . $del_id . ': ' .
                    mysqli_error($conn)
                );
                break;
            }
        }

        if ($delete_ok) {
            mysqli_commit($conn);
            header("Location: profile.php?success=post_deleted");
        } else {
            mysqli_rollback($conn);
            header("Location: profile.php?error=failed_to_delete");
        }
    } else {
        header("Location: profile.php?error=post_not_found");
    }

    exit();
}
    /* ==================================
    CONFIRM DELIVERY & UPDATE STATUS
    ================================== */
    if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['confirm_delivery'])) {
        $delivery_id = (int)$_POST['delivery_id'];
        $receiver_location = mysqli_real_escape_string($conn, $_POST['receiver_location']);
        $receiver_phone = mysqli_real_escape_string($conn, $_POST['receiver_phone']); 

        $delivery_info_query = mysqli_query($conn, "SELECT sender_id FROM delivery_request WHERE id = $delivery_id");
        $delivery_info = mysqli_fetch_assoc($delivery_info_query);
        $sender_id = $delivery_info['sender_id'];

        $update_query = "
            UPDATE delivery_request 
            SET receiver_location = '$receiver_location',
                receiver_phone = '$receiver_phone',
                delivery_status = 'waiting_driver',
                receiver_done = 1
            WHERE id = $delivery_id
        ";

        if (mysqli_query($conn, $update_query)) {

    // Fetch item_id to update post status
    $post_id_query = mysqli_query($conn, "SELECT item_id FROM delivery_request WHERE id = $delivery_id");
    $post_id_row = mysqli_fetch_assoc($post_id_query);
    $post_id = $post_id_row['item_id'];

    // Update post status to sold
    mysqli_query($conn, "UPDATE posts SET status = 'sold' WHERE id = '$post_id'");
    
            mysqli_query($conn, "
                INSERT INTO notification (
                    user_id,
                    message,
                    type,
                    related_id
                )
                VALUES (
                    '$sender_id',
                    '@$me confirmed the delivery request! Your order has been sent to delivery coordination.',
                    'delivery',
                    '$delivery_id'
                )
            ");

            header("Location: profile.php?success=delivery_confirmed");
        } else {
            header("Location: profile.php?error=failed_to_confirm");
        }
        exit();
    }

    /* ==================================
    AJAX: FETCH DELIVERY DETAILS FOR MODAL
    ================================== */
    if (isset($_POST['get_delivery_details'])) {

        header('Content-Type: application/json');

        $delivery_id = (int)$_POST['delivery_id'];

        $res = mysqli_query(
            $conn,
            "SELECT * FROM delivery_request WHERE id = $delivery_id"
        );

        if (!$res) {
            echo json_encode([
                "error" => mysqli_error($conn)
            ]);
            exit();
        }

        $details = mysqli_fetch_assoc($res);

        if (!$details) {
            echo json_encode([
                "error" => "No delivery found"
            ]);
            exit();
        }

        echo json_encode($details);
        exit();
    }
?>

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>My Profile | Swapy</title>

    <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap"
        rel="stylesheet"
    >

    <link rel="stylesheet" href="profile.css">

</head>

<body class="personal-profile-body">

    <div class="header-nav">

        <a href="../index.php" class="back-link">
            ❮ Back to Marketplace
        </a>

        <button
            class="profile-logout"
            onclick="location.href='../logout.php'"
        >
            Log Out
        </button>

    </div>

    <main class="profile-page personal-profile-page">

        <section class="profile-hero">
            <div class="profile-identity">
                <img
                    src="<?php echo !empty($user_data['pic'])
                        ? '../image.php?entity=user&amp;id=' . (int)$user_data['id'] . '&amp;v=' . time()
                        : 'https://ui-avatars.com/api/?name='.urlencode($user_data['name']); ?>"
                    class="profile-img"
                >
                <div>
                    <h1><?php echo $user_data['name']; ?></h1>
                    <p class="profile-handle">@<?php echo $me; ?></p>
                </div>
            </div>

            <div class="profile-about">
                <div class="bio-heading">
                    <span class="eyebrow">About you</span>
                    <span class="profile-status"><span></span> Active member</span>
                </div>
                <p class="bio-text">
                    <?php
                    echo htmlspecialchars(
                        $user_data['bio']
                        ?: 'Add a bio to tell people about yourself.'
                    );
                    ?>
                </p>
                <button
                    type="button"
                    class="btn btn-primary edit-profile-btn"
                    onclick="openProfileSection('edit-profile', this)"
                >
                    Edit Profile
                </button>
            </div>
        </section>

        <section class="profile-shortcuts personal-secondary-actions" aria-label="Profile sections">
            <button type="button" class="section-button" onclick="openProfileSection('messages', this)">
                <span class="section-button-icon">💬</span>
                <span>
                    <strong>Messages</strong>
                    <small>Active discussions</small>
                </span>
            </button>
            <button type="button" class="section-button" onclick="openProfileSection('notifications', this)">
                <span class="section-button-icon">🔔</span>
                <span>
                    <strong>Notifications</strong>
                    <small>Updates for you</small>
                </span>
            </button>
        </section>

        <section class="card personal-items-card" id="my-items-section">
            <div class="personal-items-heading">
                <h2>My Items</h2>
                <p>Your listings</p>
            </div>

            <?php
            $my_posts = mysqli_query(
                $conn,
                "
                SELECT *
                FROM posts
                WHERE author = '$me'
                ORDER BY id DESC
                "
            );
            if (!$my_posts || mysqli_num_rows($my_posts) === 0):
            ?>
                <div class="personal-items-empty">You haven't posted anything yet.</div>
            <?php else: ?>
                <div class="personal-posts-grid">
                    <?php while($p = mysqli_fetch_assoc($my_posts)):
                        $post_for_js = $p;
                        unset($post_for_js['img']);
                        $post_json = htmlspecialchars(json_encode($post_for_js), ENT_QUOTES, 'UTF-8');
                        $post_status = strtolower((string) $p['status']);
                        $post_status_label = ucfirst($post_status);
                    ?>
                        <article class="personal-post">
                            <span class="personal-post-tag">
                                <?php echo htmlspecialchars($p['category']); ?>
                            </span>
                            <button
                                type="button"
                                class="personal-post-edit"
                                onclick='openEditModal(<?php echo $post_json; ?>)'
                                aria-label="Edit <?php echo htmlspecialchars($p['title']); ?>"
                            >
                                Edit
                            </button>
                            <img
                                src="<?php echo '../image.php?entity=post&amp;id=' . (int)$p['id']; ?>"
                                alt="<?php echo htmlspecialchars($p['title']); ?>"
                            >
                            <div class="personal-post-info">
                                <span class="personal-post-status status-<?php echo htmlspecialchars($post_status); ?>">
                                    <?php echo htmlspecialchars($post_status_label); ?>
                                </span>
                                <strong><?php echo htmlspecialchars($p['title']); ?></strong>
                                <small>
                                    <?php echo $p['type'] === 'Sell'
                                        ? htmlspecialchars($p['price']) . ' JD'
                                        : '🔄 Swap'; ?>
                                </small>
                                <div class="personal-post-actions">
                                    <button
                                        type="button"
                                        class="btn btn-danger"
                                        onclick="if(confirm('Delete?')) location.href='profile.php?delete_id=<?php echo (int)$p['id']; ?>'"
                                    >
                                        Delete
                                    </button>
                                </div>
                            </div>
                        </article>
                    <?php endwhile; ?>
                </div>
            <?php endif; ?>
        </section>

        <div class="content-section" id="sectionWindows">

            <button
                type="button"
                class="section-window-close"
                onclick="closeProfileSection()"
                aria-label="Close profile section"
            >
                ×
            </button>

            <div class="card section-card profile-edit-panel" id="edit-profile-panel">
                <div class="section-card-heading">
                    <div>
                        <h3>Edit Profile</h3>
                        <p>Update your bio or choose a profile picture.</p>
                    </div>
                </div>

                <form
                    method="POST"
                    action="profile.php"
                    class="profile-edit-form"
                    enctype="multipart/form-data"
                >
                    <label for="profile-bio">Bio</label>
                    <textarea
                        id="profile-bio"
                        name="bio"
                        rows="4"
                        maxlength="1000"
                    ><?php echo htmlspecialchars($user_data['bio'] ?? ''); ?></textarea>

                    <label for="profile-image-input">Profile Picture</label>
                    <input
                        id="profile-image-input"
                        type="file"
                        name="profile_image"
                        accept="image/jpeg,image/png,image/gif,image/webp"
                        onchange="encodeImage(this)"
                    >
                    <input
                        type="hidden"
                        name="pic_base64"
                        id="pic_base64"
                    >
                    <input
                        type="hidden"
                        name="remove_profile_image"
                        id="remove_profile_image"
                        value="0"
                    >

                    <div class="profile-image-actions">
                        <button
                            type="button"
                            class="btn btn-outline"
                            onclick="removeProfileImage()"
                        >
                            Remove image / Use default
                        </button>
                        <small id="profile-image-status">
                            JPG, PNG, GIF, or WebP
                        </small>
                    </div>

                    <div class="profile-edit-actions">
                        <button
                            type="submit"
                            name="update_profile"
                            class="btn btn-primary"
                        >
                            Save Changes
                        </button>
                        <button
                            type="button"
                            class="btn btn-outline"
                            onclick="closeProfileSection()"
                        >
                            Cancel
                        </button>
                    </div>
                </form>
            </div>

            <div class="card section-card" id="messages-panel">

                <?php

                $inbox_res = mysqli_query(
                    $conn,
                    "
                    SELECT
                        c.item_id,
                        p.title,
                        p.img,
                        CASE
                            WHEN c.sender = '$me'
                            THEN c.receiver
                            ELSE c.sender
                        END as chat_partner
                    FROM chats c
                    JOIN posts p
                    ON c.item_id = p.id
                    WHERE (c.sender = '$me' OR c.receiver = '$me')
                    GROUP BY c.item_id, chat_partner
                    ORDER BY c.id DESC
                    "
                );

                if(mysqli_num_rows($inbox_res) == 0){

                    echo "
                    <p style='color:gray; font-size:13px;'>
                        No active chats yet.
                    </p>
                    ";

                }

                while($row = mysqli_fetch_assoc($inbox_res)):

                ?>

                <div
                    class="item-row"
                    style="cursor:pointer;"
                    onclick='openInbox(
                        <?php echo json_encode($row); ?>,
                        "<?php echo $row['chat_partner']; ?>"
                    )'
                >

                    <img src="<?php echo '../image.php?entity=post&amp;id=' . (int)$row['item_id']; ?>" alt="">

                    <div style="flex:1;">

                        <b><?php echo $row['title']; ?></b>

                        <small style="color:gray;">
                            Chatting with
                            @<?php echo $row['chat_partner']; ?>
                        </small>

                    </div>

                    <span style="
                        color:var(--primary);
                        font-size:20px;
                    ">
                        ❯
                    </span>

                </div>

                <?php endwhile; ?>

            </div>

            <div class="card section-card" id="notifications-panel">

                <?php

                $notif_res = mysqli_query($conn, "
                    SELECT
                        n.*,
                        d.delivery_status,
                        d.sender_id,
                        d.receiver_id,
                        d.driver_id,
                        p.id AS delivery_item_id,
                        p.title AS delivery_item_title,
                        p.img AS delivery_item_img,
                        sender_user.name AS delivery_sender_name,
                        receiver_user.name AS delivery_receiver_name,
                        driver.name AS delivery_driver_name,
                        driver.pic AS delivery_driver_pic
                    FROM notification n
                    LEFT JOIN delivery_request d ON n.related_id = d.id AND n.type = 'delivery'
                    LEFT JOIN posts p ON d.item_id = p.id AND n.type = 'delivery'
                    LEFT JOIN users sender_user ON d.sender_id = sender_user.id AND n.type = 'delivery'
                    LEFT JOIN users receiver_user ON d.receiver_id = receiver_user.id AND n.type = 'delivery'
                    LEFT JOIN users driver ON d.driver_id = driver.id AND n.type = 'delivery'
                    WHERE n.user_id = (SELECT id FROM users WHERE username='$me')
                    ORDER BY n.id DESC
                ");

                if(!$notif_res){
                    die(mysqli_error($conn));
                }

                if(mysqli_num_rows($notif_res) == 0){

                    echo "
                    <p style='color:gray; font-size:13px;'>
                        No notifications yet.
                    </p>
                    ";

                }

            while($n = mysqli_fetch_assoc($notif_res)): 
                $my_id = $user_data['id']; 
            ?>

            <div style="padding: 15px 20px; border: 1px solid #e2e8f0; border-radius: 16px; margin-bottom: 12px; background: #fffdf5; display: flex; justify-content: space-between; align-items: center; gap: 15px;">
                <div style="display: flex; align-items: center; gap: 12px; min-width: 0;">
                    <div style="display: flex; align-items: center; gap: 5px; flex-shrink: 0;">
                        <?php if($n['type'] === 'delivery' && !empty($n['delivery_item_id']) && !empty($n['delivery_item_img'])): ?>
                            <img
                                src="../image.php?entity=post&amp;id=<?php echo (int)$n['delivery_item_id']; ?>"
                                alt="Order"
                                style="width: 48px; height: 48px; object-fit: cover; border-radius: 10px; border: 1px solid #e2e8f0;"
                            >
                        <?php endif; ?>

                        <?php if($n['type'] === 'delivery' && !empty($n['driver_id']) && !empty($n['delivery_driver_pic'])): ?>
                            <img
                                src="../image.php?entity=user&amp;id=<?php echo (int)$n['driver_id']; ?>"
                                alt="Driver"
                                title="<?php echo htmlspecialchars($n['delivery_driver_name'] ?: 'Driver'); ?>"
                                style="width: 34px; height: 34px; object-fit: cover; border-radius: 50%; border: 2px solid #fff; box-shadow: 0 1px 4px rgba(15,23,42,.15);"
                            >
                        <?php elseif($n['type'] === 'delivery' && empty($n['delivery_item_img'])): ?>
                            <span style="width: 48px; height: 48px; border-radius: 10px; background: #fef3c7; display: inline-flex; align-items: center; justify-content: center; font-size: 22px;" aria-hidden="true">🚚</span>
                        <?php endif; ?>
                    </div>

                    <div style="min-width: 0;">
                    <div style="font-weight: 600; margin-bottom: 4px; color: #1e293b;">
                        <?php 
                            echo htmlspecialchars($n['message']); 
                        ?>
                    </div>
                    <?php if($n['type'] === 'delivery' && (!empty($n['delivery_item_title']) || !empty($n['delivery_sender_name']) || !empty($n['delivery_receiver_name']) || !empty($n['delivery_driver_name']))): ?>
                        <div style="font-size: 11px; color: #64748b; margin-bottom: 4px;">
                            <?php if(!empty($n['delivery_item_title'])): ?>
                                Order: <?php echo htmlspecialchars($n['delivery_item_title']); ?>
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_item_title']) && (!empty($n['delivery_sender_name']) || !empty($n['delivery_receiver_name']) || !empty($n['delivery_driver_name']))): ?>
                                &nbsp;·&nbsp;
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_sender_name'])): ?>
                                Sender: <?php echo htmlspecialchars($n['delivery_sender_name']); ?>
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_sender_name']) && (!empty($n['delivery_receiver_name']) || !empty($n['delivery_driver_name']))): ?>
                                &nbsp;·&nbsp;
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_receiver_name'])): ?>
                                Receiver: <?php echo htmlspecialchars($n['delivery_receiver_name']); ?>
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_receiver_name']) && !empty($n['delivery_driver_name'])): ?>
                                &nbsp;·&nbsp;
                            <?php endif; ?>
                            <?php if(!empty($n['delivery_driver_name'])): ?>
                                Driver: <?php echo htmlspecialchars($n['delivery_driver_name']); ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <small style="color: gray; font-size: 11px;"><?php echo $n['created_at']; ?></small>
                    </div>
                </div>

                <?php if($n['type'] === 'delivery'): ?>
                    
                    <?php if($my_id == $n['sender_id']): ?>
                        <?php if($n['delivery_status'] === 'waiting_for_other_user'): ?>
                        <?php elseif($n['delivery_status'] === 'waiting_driver'): ?>
                        <?php endif; ?>

                    <?php elseif($my_id == $n['receiver_id']): ?>
                        <?php if($n['delivery_status'] === 'waiting_for_other_user'): ?>
                            <button type="button" class="btn btn-outline" style="padding: 6px 14px; font-size: 13px; white-space: nowrap;"
                                    onclick="openIncomingDeliveryModal(<?php echo $n['related_id']; ?>)">
                                Confirm & Enter Details
                            </button>
                        <?php elseif($n['delivery_status'] === 'waiting_driver'): ?>
                            <span style="color: #10b981; font-size: 13px; font-weight: 600; white-space: nowrap;">✓ Confirmed</span>
                        <?php endif; ?>
                        
                    <?php endif; ?>

                <?php endif; ?>
            </div>

            <?php endwhile; ?>

            </div>

        </div>

    </main>

    <div id="inboxModal" class="modal">

        <div class="modal-content inbox-modal-content">

            <div class="inbox-header">

                <h3 id="inbox_title">
                    Chat
                </h3>

                <button
                    class="btn btn-danger inbox-close"
                    onclick="
                        this.closest('.modal').style.display='none'
                    "
                >
                    Close
                </button>

            </div>

            <div id="inbox_msgs"></div>

            <div class="inbox-composer">

                <input
                    type="text"
                    id="inbox_input"
                    placeholder="Type your reply..."
                >

                <button
                    onclick="sendInboxMsg()"
                    id="send-btn"
                    class="btn btn-primary"
                >
                    Send
                </button>

            </div>

        </div>

    </div>

    <div id="editItemModal" class="modal">

        <div class="modal-content">

            <h3>Edit Listing</h3>

            <form method="POST" action="profile.php">

                <input
                    type="hidden"
                    name="p_id"
                    id="edit_p_id"
                >

                <label style="
                    font-size:13px;
                    color:#64748b;
                ">
                    Item Title
                </label>

                <input
                    type="text"
                    name="title"
                    id="edit_title"
                    required
                >

                <label style="
                    font-size:13px;
                    color:#64748b;
                ">
                    Description
                </label>

                <textarea
                    name="description"
                    id="edit_desc"
                    rows="4"
                    required
                ></textarea>

                <div style="
                    display:flex;
                    gap:10px;
                    margin-top:10px;
                ">

                    <button
                        type="submit"
                        name="edit_item"
                        class="btn btn-primary"
                        style="flex:1;"
                    >
                        Update Item
                    </button>

                    <button
                        type="button"
                        class="btn btn-outline"
                        onclick="
                            document.getElementById(
                                'editItemModal'
                            ).style.display='none'
                        "
                    >
                        Cancel
                    </button>

                </div>

            </form>

        </div>

    </div>

    <div id="incomingDeliveryModal" class="modal" onclick="if(event.target==this) closeIncomingModal()">
        <div class="modal-content" style="max-width:500px; padding:30px; display:block; border-radius:24px;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;">
                <div>
                    <h3 style="margin:0;">Delivery Request Details</h3>
                    <p style="margin-top:4px; color:#64748b; font-size:13px; font-weight: normal;">Provide your details to confirm the delivery</p>
                </div>
                <button type="button" onclick="closeIncomingModal()" style="border:none; background:#f1f5f9; width:34px; height:34px; border-radius:10px; cursor:pointer; font-weight:bold;">✕</button>
            </div>

            <div style="background: #f8fafc; padding: 12px; border-radius: 12px; margin-bottom: 15px; border: 1px dashed #cbd5e1;">
                <span style="font-size: 12px; color: #64748b; font-weight: 600;">Sender's Info (Read-only):</span>
                <p style="margin: 5px 0 2px 0; font-size: 13px;"><b>Pickup From:</b> <span id="view_sender_location"></span></p>
                <p style="margin: 0; font-size: 13px;"><b>Notes:</b> <span id="view_delivery_notes"></span></p>
            </div>

            <form method="POST" action="profile.php">
                <input type="hidden" name="confirm_delivery" value="1">
                <input type="hidden" name="delivery_id" id="inc_delivery_id">
                
                <div style="margin-bottom: 15px; text-align: left;">
                    <label style="font-size:13px; color:#64748b; display:block; margin-bottom:5px; font-weight:600;">Your Drop-off Location (Receiver Location)</label>
                    <input type="text" name="receiver_location" placeholder="Enter your full address" required style="width:100%; padding:10px; border:1px solid #e2e8f0; border-radius:10px; outline:none; font-family:inherit;">
                </div>

                <div style="margin-bottom: 20px; text-align: left;">
                    <label style="font-size:13px; color:#64748b; display:block; margin-bottom:5px; font-weight:600;">Your Contact Phone Number</label>
                    <input type="text" name="receiver_phone" placeholder="07xxxxxxxx" required style="width:100%; padding:10px; border:1px solid #e2e8f0; border-radius:10px; outline:none; font-family:inherit;">
                </div>

                <button type="submit" class="btn btn-primary" style="width:100%; padding:12px; font-weight:600; font-size:14px; background: #10b981; border: none; border-radius:12px;">
                    Confirm & Request Driver
                </button>
            </form>
        </div>
    </div>

    <div id="receiptModal" class="modal" onclick="if(event.target==this) closeReceiptModal()">
        <div class="modal-content" style="max-width:450px; padding:30px; display:block; border-radius:24px;">
            <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:20px;">
                <div>
                    <h3 style="margin:0;">Delivery Receipt</h3>
                    <p style="margin-top:4px; color:#10b981; font-size:13px; font-weight: 600;">✓ Confirmed & Waiting Driver</p>
                </div>
                <button type="button" onclick="closeReceiptModal()" style="border:none; background:#f1f5f9; width:34px; height:34px; border-radius:10px; cursor:pointer; font-weight:bold;">✕</button>
            </div>

            <div style="margin-bottom: 15px; text-align: left;">
                <label style="font-size:13px; color:#64748b; display:block; margin-bottom:5px;">Your Saved Location</label>
                <input type="text" id="rec_user_location" readonly style="background:#f8fafc; color:#1e293b; width:100%; padding:10px; border:1px solid #e2e8f0; border-radius:10px; outline:none;">
            </div>

            <div style="margin-bottom: 15px; text-align: left;">
                <label style="font-size:13px; color:#64748b; display:block; margin-bottom:5px;">Delivery Notes</label>
                <textarea id="rec_delivery_notes" rows="3" readonly style="background:#f8fafc; color:#1e293b; width:100%; padding:10px; border:1px solid #e2e8f0; border-radius:10px; outline:none; resize:none;"></textarea>
            </div>
            
            <button type="button" onclick="closeReceiptModal()" class="btn btn-outline" style="width:100%; padding:11px; border-radius:12px;">Close</button>
        </div>
    </div>
    <script>

    function openProfileSection(sectionName, button) {
        const sectionWindows = document.getElementById('sectionWindows');
        const selectedPanel = document.getElementById(sectionName + '-panel');

        sectionWindows.querySelectorAll('.section-card').forEach(function(panel) {
            panel.classList.remove('is-open');
        });

        document.querySelectorAll('.section-button').forEach(function(sectionButton) {
            sectionButton.classList.remove('is-active');
        });

        if (!selectedPanel) return;

        selectedPanel.classList.add('is-open');
        sectionWindows.classList.add('is-open');
        sectionWindows.scrollTop = 0;
        if (button) button.classList.add('is-active');
        document.body.classList.add('profile-window-open');
    }

    function closeProfileSection() {
        const sectionWindows = document.getElementById('sectionWindows');
        sectionWindows.classList.remove('is-open');
        sectionWindows.querySelectorAll('.section-card').forEach(function(panel) {
            panel.classList.remove('is-open');
        });
        document.body.classList.remove('profile-window-open');
    }

    document.addEventListener('keydown', function(event) {
        if (event.key === 'Escape') {
            closeProfileSection();
        }
    });

    let currentInboxId = null;

    let currentPartner = "";

    const messageInput =
        document.getElementById("inbox_input");

    messageInput.addEventListener(
        "keydown",
        function(event){

            if(event.key == "Enter"){

                event.preventDefault();

                sendInboxMsg();

            }

        }
    );

    function openInbox(item, partner) {

        currentInboxId = item.item_id;

        currentPartner = partner;

        const profileLink = `
        <a
            href="other_profile.php?user=${partner}"
            style="
                text-decoration:none;
                font-size:12px;
                color:var(--primary);
                margin-left:10px;
                font-weight:normal;
            "
        >
            (View Profile)
        </a>
        `;

        document.getElementById(
            'inbox_title'
        ).innerHTML =
            item.title +
            " (@" +
            partner +
            ")" +
            profileLink;

        fetchInbox();

        document.getElementById(
            'inboxModal'
        ).style.display = 'flex';
    }

    function fetchInbox() {

        if(!currentInboxId) return;

        const fd = new FormData();

        fd.append('fetch_msgs', '1');

        fd.append('item_id', currentInboxId);

        fd.append('target_user', currentPartner);

        fetch(
            '../index.php',
            {
                method: 'POST',
                body: fd
            }
        )

        .then(r => r.json())

        .then(data => {

            const box =
                document.getElementById('inbox_msgs');

            box.innerHTML = "";

            data.forEach(m => {

                const isMe =
                    m.sender === "<?php echo $me; ?>";

                box.innerHTML += `
                <div class="
                    msg-bubble
                    ${isMe ? 'msg-me' : 'msg-them'}
                ">

                    <small style="
                        opacity:0.6;
                        display:block;
                        font-size:10px;
                    ">
                        @${m.sender}
                    </small>

                    ${m.message}

                </div>
                `;

            });

            box.scrollTop = box.scrollHeight;

        });

    }

    function sendInboxMsg() {

        const txt =
            document.getElementById(
                'inbox_input'
            ).value;

        if(!txt || !currentPartner) return;

        const fd = new FormData();

        fd.append('send_msg', '1');

        fd.append('item_id', currentInboxId);

        fd.append('message', txt);

        fd.append('target_user', currentPartner);

        fetch(
            '../index.php',
            {
                method: 'POST',
                body: fd
            }
        )

        .then(() => {

            document.getElementById(
                'inbox_input'
            ).value = "";

            fetchInbox();

        });

    }

    function encodeImage(input) {

        document.getElementById('remove_profile_image').value = '0';
        document.getElementById('profile-image-status').textContent =
            'New image selected';

        if (input.files && input.files[0]) {

            const reader = new FileReader();

            reader.onload = function(e) {

                document.getElementById(
                    'pic_base64'
                ).value = e.target.result;

            }

            reader.readAsDataURL(input.files[0]);

        }

    }

    function removeProfileImage() {
        const fileInput = document.getElementById('profile-image-input');
        const imageValue = document.getElementById('pic_base64');

        fileInput.value = '';
        imageValue.value = '';
        document.getElementById('remove_profile_image').value = '1';
        document.getElementById('profile-image-status').textContent =
            'Default avatar will be used after saving';
    }

    function openEditModal(item) {

        document.getElementById(
            'edit_p_id'
        ).value = item.id;

        document.getElementById(
            'edit_title'
        ).value = item.title;

        document.getElementById(
            'edit_desc'
        ).value = item.description;

        document.getElementById(
            'editItemModal'
        ).style.display = 'flex';

    }

    function openIncomingDeliveryModal(deliveryId) {

        const fd = new FormData();

        fd.append("get_delivery_details", "1");

        fd.append("delivery_id", deliveryId);

        fetch("profile.php", {
            method: "POST",
            body: fd
        })

        .then(res => res.text())

        .then(data => {

            console.log(data);

            const json = JSON.parse(data);

            if(json.error){
                alert(json.error);
                return;
            }

            document.getElementById(
                "view_sender_location"
            ).innerText = json.sender_location;

            document.getElementById(
                "view_delivery_notes"
            ).innerText =
                json.delivery_notes
                ? json.delivery_notes
                : "No notes.";

            document.getElementById(
                "inc_delivery_id"
            ).value = json.id;

            document.getElementById(
                "incomingDeliveryModal"
            ).style.display = "flex";

        })

        .catch(err => console.error(err));
    }


    function closeIncomingModal() {
        document.getElementById("incomingDeliveryModal").style.display = "none";
    }

    const currentSessionUser = "<?php echo $me; ?>";

    function openReceiptModal(deliveryId) {
        const fd = new FormData();
        fd.append("get_delivery_details", "1");
        fd.append("delivery_id", deliveryId);

        fetch("profile.php", {
            method: "POST",
            body: fd
        })
        .then(res => res.json())
        .then(data => {
            if(data) {
                if(currentSessionUser === data.sender_username) {
                    document.getElementById("rec_user_location").value = data.sender_location;
                } else {
                    document.getElementById("rec_user_location").value = data.receiver_location;
                }
                
                document.getElementById("rec_delivery_notes").value = data.delivery_notes ? data.delivery_notes : "No notes provided.";
                
                document.getElementById("receiptModal").style.display = "flex";
            }
        })
        .catch(err => console.error("Error loading receipt details:", err));
    }

    function closeReceiptModal() {
        document.getElementById("receiptModal").style.display = "none";
    }
    </script>

</body>

</html>